### ISSUE TITLE
[1] "[0]" must not be a sparse array item

### ISSUE THREAD

**Issue by albertpeiro** [tjdavey/joi-tz#19]
I installed:

```json
"joi": "^17.6.0",
"joi-tz": "^4.1.1",
```

and coded:

```typescript
import * as BaseJoi from "joi";
import JoiTimezone from "joi-tz";
const Joi = BaseJoi.extend(JoiTimezone);

const querySchema = Joi.object({
  rangeStart: Joi.date().required(),
  rangeEnd: Joi.date().required(),
  rangeTz: Joi.string().required(),
});
```

Didn't call `.timezone()` yet but it already seems to break BaseJoi. Is there anything I'm doing wrong?
I've tried downgrading to joi 16, 17.5, 17.4 but didn't help.

```bash
/Users/albert.peiro/Development/hero/vs-dashboard-api/node_modules/joi/lib/errors.js:193
        return new exports.ValidationError(message, details, original);
               ^
Error [ValidationError]: [
  null
]

[1] "[0]" must not be a sparse array item
    at Object.exports.process (/Users/albert.peiro/Development/hero/vs-dashboard-api/node_modules/joi/lib/errors.js:193:16)
    at Object.internals.entry (/Users/albert.peiro/Development/hero/vs-dashboard-api/node_modules/joi/lib/validator.js:153:26)
    at Object.exports.entry (/Users/albert.peiro/Development/hero/vs-dashboard-api/node_modules/joi/lib/validator.js:27:30)
    at internals.Base.validate (/Users/albert.peiro/Development/hero/vs-dashboard-api/node_modules/joi/lib/base.js:548:26)
    at Object.internals.assert (/Users/albert.peiro/Development/hero/vs-dashboard-api/node_modules/joi/lib/index.js:225:27)
    at Object.assert (/Users/albert.peiro/Development/hero/vs-dashboard-api/node_modules/joi/lib/index.js:102:19)
    at Object.extend (/Users/albert.peiro/Development/hero/vs-dashboard-api/node_modules/joi/lib/index.js:156:14)
    at Object.<anonymous> (/Users/albert.peiro/Development/hero/vs-dashboard-api/src/routes/middlewares/HomeOverview.ts:5:21)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (/Users/albert.peiro/Development/hero/vs-dashboard-api/node_modules/ts-node/src/index.ts:1618:23) {
  _original: [ undefined ],
  details: [
    {
      message: '"[0]" must not be a sparse array item',
      path: [Array],
      type: 'array.sparse',
      context: [Object]
    }
  ]
}
```

**Comment by tjdavey** [comment]
@albertpeiro I've been unable to reproduce this in Node 18 or Node 16 using the example you gave and some expansion. This is the code I tested with. 

```
import BaseJoi from "joi";
import JoiTimezone from "joi-tz";
const Joi = BaseJoi.extend(JoiTimezone);

const querySchema = Joi.object({
    rangeStart: Joi.date().required(),
    rangeEnd: Joi.date().required(),
    rangeTz: Joi.string().required(),
});

const result = querySchema.validate({
    rangeStart: '2022-01-01',
    rangeEnd: '2022-01-03',
    rangeTz: 'Asia/Bangkok',
});

console.log(result);
```

The error you have provided indicates a validation error in a Joi schema containing an `array` type. There isn't one included in this code. Are you able to provide me with a little more detail in the environment you're seeing this issue in, and maybe a full example file?

**Comment by ckrusepmc** [comment]
I'm getting the same error on my end. I'm also not using `array()`. If I remove `joi-tz`, the error goes away. It might be worth noting that I'm using `moment-timezone` in my project already. 

My schema:
```
export const LocationValidator = Joi.object({
  name: Joi.string().required(),
  // timezone: Joi.timezone(),
  address: Joi.object({
    line_1: Joi.string(),
    line_2: Joi.string(),
    city: Joi.string(),
    state: Joi.string(),
    postcode: Joi.string(),
  }),
});
```

**Comment by cursomeancore** [comment]
Any solution for this problem?

**Comment by tjdavey** [comment]
There have been no recent reports of this issue and no further debug information provided by the original poster. I'm happy to reopen this if we believe it isn't resolved. But for the sake of cleanliness I'm going to close this unless we discover this is still an ongoing issue.
